language: php

php:
  - "7.2"
  - "7.3"
  - "7.4"

install:
  - composer update --no-interaction --no-suggest --no-progress

script:
  - vendor/bin/phpunit

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
